name: 'Simple web page source code downloader'
description: 'An action which downloads the page source code.'
metadata:
  author: 'siddhartasr10'
  forked-from: 'SimpERROR_'

branding: 
  icon: download-cloud
  color: purple

inputs:
  include-index:
    description: 'Whether to copy an index.html helper into each site folder'
    required: true
    default: true 

  save-css:
    description: 'Choose if you want to save the site css'
    required: true
    default: true 

  skip-on-throw:
    description: 'Whether to skip a page if it throws an error o try again'
    required: true
    default: false

outputs:
  source-paths:
    description: 'The path to the saved html file.'
    value: ${{ steps.run-step.outputs.html-path }}
  status:
    description: 'The status of the download operation (success/failed).'
    value: ${{ steps.run-step.outputs.status }}
  time:
    description: 'The time when the download was made.'
    value: ${{ steps.run-step.outputs.time }}

runs:
  using: 'node24'
  main: 'dist/index.js'
