name: 'Simple web page source code downloader'
description: 'An action which downloads the page source code.'
metadata:
  author: 'siddhartasr10'
  waitFunc: 'SimpERROR_'

branding: 
  icon: download-cloud
  color: purple

inputs:
  website:
    description: 'The website to download.'
    required: true
    default: 'https://www.bilibili.com/video/BV1GJ411x7h7'

outputs:
  html-path:
    description: 'The path to the saved html file.'
    value: ${{ steps.run-step.outputs.html-path }}
  status:
    description: 'The status of the download operation (success/failed).'
    value: ${{ steps.run-step.outputs.status }}
  time:
    description: 'The time when the download was made.'
    value: ${{ steps.run-step.outputs.time }}

runs:
  using: 'node20'
  main: 'dist/index.js'
