  name: main

  on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * *"

  permissions: 
    contents: write

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Setup Chromium
          uses: browser-actions/setup-chrome@v1
          id: setup-chrome
          with:
            chrome-version: stable

        - run: npm ci && npm run all

        - name: get source-code
          id: snapshot_step
          uses: ./
          with: # Default values are set explictly only for documentation purposes
            include-index: true
            save-css: true
            skip-on-throw: false
          env:
            PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}

        - name: GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./sites
            publish_branch: gh-pages
            keep_files: true
